# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf-spring-app
  labels:
    app: mf-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mf-spring-app
  template:
    metadata:
      labels:
        app: mf-spring-app
    spec:
      containers:
      - name: mf-spring-app
        image: "replace"
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true



