resources:
 - ../../base/mf-qm01
 # - queuemanager/hooks/post-sync-job.yaml
 # - certificates/staging-mf-client-certificate.yaml
 # - certificates/staging-mf-server-certificate.yaml
 # - secrets/mf-client-jks-password-secret.yaml
 - roles/cphtestp-clusterrole.yaml
 - roles/cphtestp-sa-rolebinding.yaml

# Add the configMap that will be used for dynamic updates, this should be used queue manager wide i.e. stay the same in each environment.
components:
- components/dynamic-mfsc/generic-qmgr
- components/scripts

generatorOptions:
 disableNameSuffixHash: true
# We use a configMapGenerator because it allows us to build up the mfsc from regular mfSC files.
configMapGenerator:
# Create an mfSC configMap using generic mfSC which will be added to all queue managers and applied during bootstrap.
- name: mfsc-configmap
  behavior: create
  files:
  - configmap/static-definitions.mfsc
patchesStrategicMerge:
 - queuemanager/queuemanager.yaml
 - components/dynamic-mfsc/generic-qmgr/queuemanager.yaml
