# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf-spring-app
  labels:
    app.kubernetes.io/name: mf-spring-app
    helm.sh/chart: mf-spring-app-1.0.0-rc0.0.2
    app.kubernetes.io/instance: mf-spring-app
    app: mf-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mf-spring-app
  template:
    metadata:
      labels:
        app: mf-spring-app
    spec:
      containers:
      - name: mf-spring-app
        image: "image-registry.openshift-image-registry.svc:5000/ci/mf-spring-app:0.0.4"
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true



