apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-mf-metric-samples-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mf/environments/staging/mf-metric-samples/
    repoURL: https://github.com/mf-devops-java/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
