apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: mf-devops-java
  owner: mf-devops-java
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/mf-devops-java/multi-tenancy-gitops-apps.git
