apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-s2i
  annotations:
    app.openshift.io/runtime: openjdk
    app.openshift.io/builder: maven
spec:
 pipelineSpec:
  # workspaces:
  #   - name: shared-workspace
  #   - name: sslcertdir
  #     optional: true
  params:
    - name: git-url
      description: The url for the git repository
    - name: git-revision
      description: The git revision (branch, tag, or sha) that should be built
      default: master
    - name: scan-image
      description: Enable the pipeline to scan the image for vulnerabilities
      default: "false"
    - name: BUILDER_IMAGE
      description: The url for the git repository
    - name: TLSVERIFY
      description: The url for the git repository
    - name: LOGLEVEL
      description: The url for the git repository
    - name: IMAGE
      description: The url for the git repository
  tasks:
    - name: setup
      taskRef:
        name: ibm-setup-v2-6-13
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: scan-image
          value: $(params.scan-image)
    # - name: fetch-repository
    #   taskRef:
    #     name: git-clone
    #   workspaces:
    #     - name: output
    #       workspace: shared-workspace
    #   params:
    #     - name: url
    #       value: $(params.url)
    #     - name: subdirectory
    #       value: $(params.subdirectory)
    #     - name: deleteExisting
    #       value: $(params.deleteExisting)
    - name: s2i
      taskRef:
        name: s2i
      runAfter:
        - setup
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
        - name: TLSVERIFY
          value: $(params.TLSVERIFY)
        - name: LOGLEVEL
          value: $(params.LOGLEVEL)
        - name: IMAGE
          value: $(params.IMAGE)
  workspaces:
    - name: shared-workspace
    - name: sslcertdir
      optional: true
      # volumeClaimTemplate:
      #   spec:
      #     accessModes:
      #       - ReadWriteOnce
      #     resources:
      #       requests:
      #         storage: 100Mi